import type { Database as SqliteDatabase } from 'bun:sqlite';
import { describe, expect, test } from 'bun:test';
import { decryptSecret, encryptSecret } from '../src/crypto.js';
import { importLegacyMetadata, metadataCounts, openDatabase, parameterMap, Repository, validateTelemetryParameters } from '../src/repository.js';
import { isConfigured, loadConfig } from '../src/config.js';
import { createDeviceSchema, telemetrySchema } from '../src/validation.js';
import type { Device, EncryptedSecret } from '../src/types.js';
const key = new Uint8Array(32).fill(7); const parameters = parameterMap([{ id: 'temperature', label: 'Suhu', unit: 'C', points: 2 }, { id: 'humidity', label: 'Kelembapan', unit: '%', points: 1 }]); const secret: EncryptedSecret = { iv: 'iv-value', ciphertext: 'ciphertext-value' };
const device = (id: string, ownerUid = 'owner-a'): Device => ({ id, ownerUid, label: id, active: true, credentialVersion: 1, createdAt: 1, updatedAt: 1, parameters });
function memoryDatabase(): SqliteDatabase { return openDatabase(':memory:'); }
function importInput(devices: Device[]) { return { devices: Object.fromEntries(devices.map((d) => [d.id, d])), access: Object.fromEntries(devices.map((d) => [d.id, { ownerUid: d.ownerUid, active: d.active, credentialVersion: d.credentialVersion }])), secrets: Object.fromEntries(devices.map((d) => [d.id, secret])) }; }
describe('security and SQLite primitives', () => {
 test('AES-GCM encrypts and decrypts', async () => { const encrypted = await encryptSecret('device-secret-value', key); expect(encrypted.ciphertext).not.toContain('device-secret-value'); expect(await decryptSecret(encrypted, key)).toBe('device-secret-value'); });
 test('SQLite filters ownership and persists telemetry deduplicated', () => { const db = memoryDatabase(); const repo = new Repository(db); repo.saveDeviceBundle(device('mine'), secret); repo.saveDeviceBundle(device('theirs', 'owner-b'), secret); expect(repo.listDevices('owner-a').map((d) => d.id)).toEqual(['mine']); const packet = { timestamp: 10, writeId: 'write-a', credentialVersion: 1, values: { temperature: { status: 'ok' as const, value: 20 }, humidity: { status: 'ok' as const, value: 30 } } }; expect(repo.saveTelemetry('mine', packet).inserted).toBe(true); expect(repo.saveTelemetry('mine', packet).inserted).toBe(false); expect(repo.getLatest('mine')).toEqual(packet); db.close(); });
 test('legacy import is idempotent and rejects conflicts', () => { const db = memoryDatabase(); const input = importInput([device('one'), device('two')]); expect(importLegacyMetadata(db, input)).toEqual({ devices: 2, inserted: 2, unchanged: 0 }); expect(importLegacyMetadata(db, input)).toEqual({ devices: 2, inserted: 0, unchanged: 2 }); expect(metadataCounts(db)).toEqual({ devices: 2, secrets: 2, owners: 1, parameters: 4 }); expect(() => importLegacyMetadata(db, importInput([{ ...device('one'), label: 'conflict' }, device('two')]))).toThrow('refusing to overwrite'); db.close(); });
 test('parameter and telemetry validation rejects malformed values', () => { expect(validateTelemetryParameters({ temperature: { status: 'ok', value: 20 }, humidity: { status: 'error', error: 'timeout' } }, parameters)).toBe(true); expect(validateTelemetryParameters({ temperature: { status: 'ok', value: 20 } }, parameters)).toBe(false); expect(telemetrySchema.safeParse({ credentialVersion: 1, timestamp: 1, writeId: 'a', values: { temperature: { status: 'failed', value: 0 } } }).success).toBe(false); });
 test('create input rejects client parameter IDs', () => { expect(createDeviceSchema.safeParse({ label: ' A ', parameters: [{ id: 'ignored', label: ' X ', unit: ' C ', points: 2 }] }).success).toBe(false); });
 test('requires only local self-hosted secrets', () => { expect(isConfigured({})).toBe(false); expect(isConfigured({ ENCRYPTION_KEY_BASE64: Buffer.alloc(32).toString('base64'), MQTT_INGEST_PASSWORD: 'x'.repeat(16) })).toBe(true); expect(() => loadConfig({ ENCRYPTION_KEY_BASE64: 'A'.repeat(44), MQTT_INGEST_PASSWORD: 'x'.repeat(16) })).toThrow('valid base64'); });
});
