per_listener_settings false
listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false
allow_zero_length_clientid false
password_file /mosquitto/auth/passwd
acl_file /mosquitto/auth/acl
check_retain_source true
max_keepalive 300
max_packet_size 131072
message_size_limit 131072
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_type error
log_type warning
log_type notice
